name: "CI"
on:
  push:
    branches:
      - "master"
      - "hotfix/**"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "docs/**"
      - "README.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest # GitHub 호스팅 런너를 사용

    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev

      - name: Install Ruby using ruby-build
        run: |
          # ruby-build 설치
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          export PATH="$HOME/.ruby-build/bin:$PATH"

          # ruby-build를 사용하여 Ruby 설치
          ruby-build ${ { matrix.ruby } } $HOME/.rbenv/versions/${ { matrix.ruby } }
          export PATH="$HOME/.rbenv/versions/${ { matrix.ruby } }/bin:$PATH"

          # Ruby 버전 확인
          ruby -v

      - name: Install Bundler
        run: gem install bundler

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test.sh
