name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: # 수동 실행 가능

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest # 윈도우 환경으로 변경

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby 3.1.0
        run: |
          Invoke-WebRequest -Uri "https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-3.1.0-1-x64.exe" -OutFile "rubyinstaller.exe"
          Start-Process -Wait -FilePath "rubyinstaller.exe" -ArgumentList "/silent"
          ruby -v  # Ruby 버전 확인
          gem install bundler  # Bundler 설치
          gem -v  # Bundler 버전 확인

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}  # GitHub Workspace로 이동
          bundle install  # 의존성 설치

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: |
          cd ${{ github.workspace }}  # GitHub Workspace로 이동
          bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest # 윈도우 환경으로 변경
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
