name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch: # 수동 실행 가능

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04 # Ubuntu 22.04 사용

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby using ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl libssl-dev libreadline-dev zlib1g-dev
          git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
          export PATH="$HOME/.ruby-build/bin:$PATH"
          ruby-build 3.2.0 /opt/hostedtoolcache/Ruby/3.2.0/x64
          touch /opt/hostedtoolcache/Ruby/3.2.0/x64.complete

      - name: Install Bundler
        run: |
          gem install bundler --user-install  # Bundler를 사용자 권한으로 설치
          echo "export PATH=\"$HOME/.gem/ruby/3.2.0/bin:$PATH\"" >> ~/.bashrc  # .bashrc에 경로 추가
          source ~/.bashrc  # 변경 사항 적용
          echo "Bundler 설치 후 PATH: $PATH"  # Bundler 경로 확인
          which bundle  # bundle 명령어 확인

      - name: Install dependencies
        run: |
          export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"  # Bundler 경로 추가
          cd $GITHUB_WORKSPACE  # 프로젝트 루트 디렉토리로 이동
          bundle install  # 의존성 설치

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: |
          cd $GITHUB_WORKSPACE  # 다시 루트 디렉토리로 이동
          bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04 # Ubuntu 22.04 사용
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
